services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "8080:80"
    depends_on:
      - backend

  

